services:
  postgres-0:
    image: postgres:15-alpine
    container_name: postgres-0
    expose:
      - "5432"
    ports:
      - "8432:5432"
    volumes:
      - "postgres-0:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=metadata
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    restart: always

  minio-0:
    image: minio/minio:latest
    container_name: minio-0
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin" 
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      - minio-0:/data
    command: server /data --console-address ":9001"

 
volumes:
  postgres-0:
    external: false
  minio-0:
    external: false